---
title: "R Notebook"
output: html_notebook
---
```{r}
remove(list = ls())
```

Datenvorbereitung
```{r}
data <- read.csv("../0_DataPreparation/preparedTrainData.csv")
names(data)
data <- data %>% arrange(Datum)
```

```{r}
n_total <- nrow(data)
n_training <- floor(0.8 * n_total)
n_validation <- floor(0.20 * n_total)
```

```{r}
training_data <-
  data %>% slice(1:n_training)
validation_data <-
  data %>% slice((n_training + 1):(n_total))
```

```{r}
data_sub1 <- subset(validation_data, Warengruppe=="1")
data_sub2 <- subset(validation_data, Warengruppe=="2")
data_sub3 <- subset(validation_data, Warengruppe=="3")
data_sub4 <- subset(validation_data, Warengruppe=="4")
data_sub5 <- subset(validation_data, Warengruppe=="5")
data_sub6 <- subset(validation_data, Warengruppe=="6")
```

Aus Baseline weiß man, dass bestes Modell mit folgenden Features:
mod10 <- lm(Umsatz ~ as.factor(Warengruppe) +  as.factor(wochentag) + KielerWoche + Temperatur + jahreszeit + Feiertag + Ferien, train_data)
```{r}
training_features <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + Warengruppe + KielerWoche + Feiertag + Ferien, training_data))
names(training_features)
```
```{r}
training_labels <- tibble(label=training_data$Umsatz)
```


```{r}
validation_features <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + as.factor(Warengruppe) + KielerWoche + Feiertag + Ferien, validation_data))
```

```{r}
validation_labels <- tibble(label=validation_data$Umsatz)
```

```{r}
features_sub1 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub1))
```

```{r}
features_sub2 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub2))
```

```{r}
features_sub3 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub3))
```

```{r}
features_sub4 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub4))
```

```{r}
features_sub5 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub5))
```

```{r}
features_sub6 <- as_tibble(model.matrix(Umsatz ~ wochentag + jahreszeit + Temperatur + KielerWoche + Feiertag + Ferien, data_sub6))
```

```{r}
labels_sub1 <- tibble(label=data_sub1$Umsatz)
```

```{r}
labels_sub2 <- tibble(label=data_sub2$Umsatz)
```

```{r}
labels_sub3 <- tibble(label=data_sub3$Umsatz)
```

```{r}
labels_sub4 <- tibble(label=data_sub4$Umsatz)
```

```{r}
labels_sub5 <- tibble(label=data_sub5$Umsatz)
```

```{r}
labels_sub6 <- tibble(label=data_sub6$Umsatz)
```

```{r}
prepared_data <- tibble(label=data$Umsatz, features) %>%  # inclusion of the dependent variable ('label')
    filter(complete.cases(.)) # Handling of missing values (here: only keeping rows without missing values)
```


```{r}
test_data = data <- read.csv("../0_DataPreparation/preparedTestData.csv")
names(test_data)
test_data <- test_data %>% arrange(Datum)

test_features <- as_tibble(model.matrix(~wochentag + jahreszeit + Temperatur + as.factor(Warengruppe) + KielerWoche + Feiertag + Ferien + id, test_data))
names(test_features)
```


```{r}
# Calculate the number of rows for each dataset
n_total <- nrow(prepared_data)
n_training <- floor(0.8 * n_total)
n_validation <- floor(0.20 * n_total)
```

```{r}
training_features <-
  prepared_data %>% select(-label) %>% slice(1:n_training)
validation_features <-
  prepared_data %>% select(-label) %>% slice((n_training + 1):(n_total))

training_labels <-
  prepared_data %>% select(label) %>% slice(1:n_training)
validation_labels <-
  prepared_data %>% select(label) %>% slice((n_training + 1):(n_total))
```

```{r}
cat("Training features dimensions:", dim(training_features), "\n")
cat("Validation features dimensions:",
    dim(validation_features),
    "\n")
cat("Training labels dimensions:", dim(training_labels), "\n")
cat("Validation labels dimensions:", dim(validation_labels), "\n")

```

```{r}
# Create subdirectory for the csv files
subdirectory <- "csv_data"
dir.create(subdirectory)

# Export of the prepared data to subdirectory
write_csv(training_features, paste0(subdirectory, "/training_features.csv"))
write_csv(validation_features, paste0(subdirectory, "/validation_features.csv"))
write_csv(training_labels, paste0(subdirectory, "/training_labels.csv"))
write_csv(validation_labels, paste0(subdirectory, "/validation_labels.csv"))
write_csv(test_features, paste0(subdirectory, "/test_features.csv"))

write_csv(features_sub1, paste0(subdirectory, "/features_sub1.csv"))
write_csv(features_sub2, paste0(subdirectory, "/features_sub2.csv"))
write_csv(features_sub3, paste0(subdirectory, "/features_sub3.csv"))
write_csv(features_sub4, paste0(subdirectory, "/features_sub4.csv"))
write_csv(features_sub5, paste0(subdirectory, "/features_sub5.csv"))
write_csv(features_sub6, paste0(subdirectory, "/features_sub6.csv"))
write_csv(labels_sub1, paste0(subdirectory, "/labels_sub1.csv"))
write_csv(labels_sub2, paste0(subdirectory, "/labels_sub2.csv"))
write_csv(labels_sub3, paste0(subdirectory, "/labels_sub3.csv"))
write_csv(labels_sub4, paste0(subdirectory, "/labels_sub4.csv"))
write_csv(labels_sub5, paste0(subdirectory, "/labels_sub5.csv"))
write_csv(labels_sub6, paste0(subdirectory, "/labels_sub6.csv"))

```

