---
title: "R-Markdown für Analyse der Datensatzmerkmale - Aufgabe Dateset Characterisristics"
author: "Gruppe 2 - Alina und Lea"
date: "2024-01-21"
output: html_document
---

```{r setup, include=FALSE}
##Analyse unseres Datensatzes (grafische Darstellung, Diagramme und Informationstabellen um Hauptmerkmale des Datensatzes zusammenzufassen)

##Informationen über: Datensatzübersicht, Fehlende Werte, Feature-Verteilungen, Korrelationen
```

```{r}
# Erstellen einer Liste mit benötigten Bibliotheken
pkgs <- c("readr", "dplyr", "lubridate", "ggplot2","DataExplorer","skimr")

# Laden der Bibliotheken und prüfen, ob sie installiert sind und gegebendenfalls installieren
for (pkg in pkgs) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}
```

```{r}
#Daten laden und warengruppen extrahieren und anzeigen einer schnellen Datenübersicht der eingelesenen Daten mit skim
umsatzdaten <- read.csv("0_DataPreparation/preparedTrainData.csv")
warengruppen_train <- unique(umsatzdaten$Warengruppe)
umsatzdaten$Datum <- as.Date(umsatzdaten$Datum)

skim(umsatzdaten)

```

```{r}
# Fehlende Werten wurden bereits bei Punkt "0_DataPreparation" bereits durch andere Werte ersetzt, wodurch jetzt hier keine fehlenden Werte mehr ersetzt werden müssen. Dies wurde mit der VIM Funktion bereit im Preperation Skript grafisch geprüft. Und hier konnte man auch anhand der skim-Übersicht gut sehen, dass keine fehlenden Werte mehr im Datensatz vorhanden sind.
```

```{r}
##Grafische Darstellung der Variable "Wochentag" mit Konfidenzintervall nach Warengruppe

# Vorbereitung der Umsatzdaten nach Wochentag getrennt nach Warengruppe
gesamtumsatz_pro_tag <- umsatzdaten %>%
  group_by(Warengruppe,wochentag) %>%
  summarise(Gesamtumsatz = sum(Umsatz),
            n=n(), 
            mean=mean(Umsatz),
            sd=sd(Umsatz)) %>%
  mutate( se=sd/sqrt(n)) %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

#Darstellen der Umsatzdaten nach Wochentag getrennt nach Warengruppe mit Konfidenzintervall
balkendiagramm_wochentag <- ggplot(gesamtumsatz_pro_tag, aes(x = wochentag, y = mean)) + facet_wrap(~Warengruppe)+
  geom_bar(stat = "identity", position = "dodge", fill="#800080", alpha=0.7)+
  geom_errorbar( aes(x=wochentag, ymin=mean-ic, ymax=mean+ic), width=0.3, colour="orange", alpha=0.9, linewidth=1.0)+
  labs(title = "Gesamtumsatz pro Tag je Warengruppe mit Konfidenzintervall", x = "Wochentag", y = "Gesamtumsatz")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Print des Balkendiagramms
print(balkendiagramm_wochentag)

```

```{r}
##Grafische Darstellung der Variable "Jahreszeit" mit Konfidenzintervall nach Warengruppe

#Vorbereiten der Umsatzdaten nach Jahreszeit getrennt nach Warengruppe
my_Warengruppe <- umsatzdaten %>%
 group_by(Warengruppe, jahreszeit) %>%
 summarise(
 n=n(),
 mean_Umsatz=mean(Umsatz),
 sd_Umsatz=sd(Umsatz)
 )%>%
 mutate( se=sd_Umsatz/sqrt(n)) %>%
 mutate( ic=se * qt((1-0.05)/2 + .5, n-1)) 

head(my_Warengruppe, 200)

print(my_Warengruppe)

#Darstellen der Umsatzdaten nach Jahreszeit getrennt nach Warengruppe mit Konfidenzintervall 
ggplot(my_Warengruppe) + facet_wrap(~Warengruppe) +
 geom_bar( aes(x=jahreszeit, y=mean_Umsatz), stat="identity",position = "dodge", fill="#800080", alpha=0.7) +
 geom_errorbar( aes(x=jahreszeit, ymin=mean_Umsatz-ic, ymax=mean_Umsatz+ic), width=0.3, colour="orange", alpha=0.9, linewidth=1.0) +
 labs(title = "Durchschnittlichtlicher Umsatz je Warengruppe nach Jahrenzeit mit Konfidenzintervall", x = "Jahreszeit", y = "Durchschnittlicher Umsatz", fill="Jahreszeit")  + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
#Darstellung des Haupteffekts "Jahreszeit" in einem Balkendiagramm
main_effect_jahreszeit <- my_Warengruppe %>%
  group_by(mean_Umsatz, jahreszeit)

print(main_effect_jahreszeit)

balkendiagramm_effect <- ggplot(main_effect_jahreszeit, aes(x = jahreszeit, y = mean_Umsatz, fill = jahreszeit)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Main Effect Jahreszeit", x = "Jahreszeit", y = "Durchschnittlicher Umsatz", fill="Jahreszeit") +
  scale_fill_brewer(palette = "Set2")

# Diagramm "Main Effect Jahreszeit" anzeigen
print(balkendiagramm_effect)

```

```{r}
#Feature-Verteilungen

```

```{r}
#Korrelationen anhand eines Teils der Daten, da andernfalls hier zu unübersichtlich 
#Beispielplot anhand der Daten my_warengruppe
plot_correlation(my_Warengruppe)

# Grafische Darstellung der Korreletion für die für uns eingefügten bzw. als relevant aus dem Trainingsdatensatz erachteten Variablen - für noch mehr variablen zu unübersichtlich. 
umsatzdaten_for_correlation <- umsatzdaten %>% select(c("Warengruppe","Umsatz","Bewoelkung","wochentag","jahreszeit","Temperatur","KielerWoche","Feiertag","Ferien"))

plot_correlation(umsatzdaten_for_correlation)

```

